Repository MeloDiary/melodiary-BE, pull requests merged in 2024-08, with the labels that each got.

#13 [Chore] github actions workflow 생성 #10
  .github/workflows/deploy.yaml
  docs/API_spec.yaml
  src/app.ts
Labels: deployment

#17 [Feat] 구글 회원가입 기능 구현 #11
  .github/workflows/deploy.yaml
  .gitignore
  app.ts
  build/.gitkeep
  build/app.js
  build/controllers/apiSpecController.js
  build/routes/apiSpecRoutes.js
  build/utils/getDirname.js
  docs/API_spec.yaml
  package-lock.json
  package.json
  src/app.ts
  src/config/.gitkeep
  src/config/dbConfig.ts
  src/config/envConfig.ts
  src/config/redisConfig.ts
  src/controllers/.gitkeep
  src/controllers/apiSpecController.ts
  src/controllers/userController.ts
  src/models/.gitkeep
  src/models/user.ts
  src/routes/.gitkeep
  src/routes/apiSpecRoutes.ts
  src/routes/authRoutes.ts
  src/routes/mateRoutes.ts
  src/routes/notificationRoutes.ts
  src/routes/userRoutes.ts
  src/services/.gitkeep
  src/services/jwtService.ts
  src/services/userService.ts
  src/types/.gitkeep
  src/types/user.ts
  src/utils/.gitkeep
  src/utils/getDirname.ts
  tsconfig.json
Labels: enhancement

#18 [Chore] 회원가입 기능 구현을 위한 Github actions 수정 #11
  .github/workflows/deploy.yaml
Labels: deployment

#19 [Feat] redis 연결 및 회원가입 기능 구현 #11
  app.ts
  docs/API_spec.yaml
  src/controllers/userController.ts
  src/models/user.ts
  src/routes/userRoutes.ts
  src/services/jwtService.ts
  src/services/userService.ts
Labels: enhancement

#21 [Feat] 닉네임 관련 API 작성 #20
  docs/API_spec.yaml
  src/controllers/userController.ts
  src/middlewares/.gitkeep
  src/middlewares/authMiddleware.ts
  src/models/user.ts
  src/models/userModel.ts
  src/routes/userRoutes.ts
  src/services/jwtService.ts
  src/services/userService.ts
  src/types/user.ts
Labels: enhancement

#34 [Feat] user 관련 API 작성 및 테스트 #31
  app.ts
  docs/API_spec.yaml
  src/controllers/userController.ts
  src/middlewares/authMiddleware.ts
  src/models/userModel.ts
  src/routes/userRoutes.ts
  src/services/jwtService.ts
  src/services/userService.ts
  src/types/user.ts
Labels: enhancement

#40 [Feat] mate, notification 관련 API 작성 및 테스트 #32
  .gitignore
  app.ts
  docs/API_spec.yaml
  docs/trigger.sql
  package-lock.json
  package.json
  src/config/awsConfig.ts
  src/controllers/awsController.ts
  src/controllers/mateController.ts
  src/controllers/notificationController.ts
  src/controllers/userController.ts
  src/models/mateModel.ts
  src/models/notificationModel.ts
  src/models/userModel.ts
  src/routes/awsRoutes.ts
  src/routes/mateRoutes.ts
  src/routes/notificationRoutes.ts
  src/services/awsService.ts
  src/services/mateService.ts
  src/services/notificationService.ts
  src/services/userService.ts
  src/types/user.ts
  src/utils/randomNickname.ts
  src/utils/s3Utils.ts
  types/woowa-babble-random-nickname.d.ts
Labels: enhancement

#48 [Fix] 504 에러 관련 개발 환경 수정 #47
  src/config/dbConfig.ts
  src/models/mateModel.ts
  src/models/notificationModel.ts
  src/models/userModel.ts
Labels: bug

#52 [Feat] 이미지 업로드 API 작성 및 테스트 #50
  app.ts
  docs/API_spec.yaml
  docs/trigger.sql
  package-lock.json
  package.json
  src/controllers/awsController.ts
  src/routes/awsRoutes.ts
  src/services/awsService.ts
  src/services/jwtService.ts
  src/services/mateService.ts
  src/services/notificationService.ts
  src/services/userService.ts
Labels: enhancement

#61 [Feat] Facebook 회원가입, 로그인 API 작성 및 테스트 #59
  src/controllers/userController.ts
  src/services/userService.ts
Labels: enhancement

#63 editted commentController.ts & api_spec.yaml
  docs/API_spec.yaml
  src/controllers/commentController.ts
Labels: enhancement

#65 [Fix] 이미지 업로드 API 수정 #64
  src/controllers/awsController.ts
Labels: bug

#69 [Feat] 카카오 회원가입, 로그인 API 작성 및 테스트 #11
  src/controllers/userController.ts
  src/services/userService.ts
Labels: enhancement
